(cons nil nil)
(list '(a b) 7 '(()))
(cons '(+ 1 2) '(+ 4 6))
(append '(+ 1 2) '())
(cons '(a (b c)) nil)
(append nil '(a b c))
(list '(+ 1 2) '() '(+ 1))
(append '(4 5 6) '() '(()))
(cons (+ 1 2) '(+ 4 6))
(list '(+ 1 2) '())