(DEFUN O(l)
(APPEND(LAST l)(CDR(BUTLAST l))(LIST(CAR l)))
)
(O '(1 2 3 4 5 6 7 8 9 10))

(DEFUN TW(l)
(APPEND(LIST(CADR l)(CAR l))(CDDR L))
)
(TW '(1 2 3 4 5 6 7 8 9))

(DEFUN TH(l)
(APPEND(LAST(BUTLAST L))(BUTLAST(BUTLAST(CDR L)))(LIST(CAR L))(LAST L))
)
(TH '(1 2 3 4 5 6 7 8 9))

(DEFUN FO(l)
(APPEND(LIST(CAR L)(CADDR l)(CADR l))(CDDDR L))
)
(FO '(1 2 3 4 5 6 7 8 9))

(DEFUN FI(l)
(APPEND(LIST(CAR L)(CADR L))(LAST L)(CDDDR(BUTLAST L))(LIST(CADDR L)))
)
(FI '(1 2 3 4 5 6 7 8 9 10))

(DEFUN SI(l)
(APPEND(LIST(CADDR L)(CADR L)(CAR L))(CDDDR L))
)
(SI '(1 2 3 4 5 6 7 8 9))

(DEFUN SE(l)
(APPEND(LIST(CAR L))(LAST L)(CDDR(BUTLAST L))(LIST(CADR L)))
)
(SE '(1 2 3 4 5 6 7 8 9 10))

(DEFUN E(l)
(APPEND(BUTLAST(BUTLAST L))(LAST L)(LAST(BUTLAST L)))
)
(E '(1 2 3 4 5 6 7 8 9))

(DEFUN N(l)
(APPEND(LIST(CAR L))(LAST(BUTLAST L))(CDDR(BUTLAST(BUTLAST L)))(LIST(CADR L))(LAST L))
)
(N '(1 2 3 4 5 6 7 8 9))

(DEFUN TEN(l)
(APPEND(LIST(CAR L)(CADR L))(LAST(BUTLAST L))(CDDDR(BUTLAST(BUTLAST L)))(LIST(CADDR L))(LAST L))
)
(TEN '(1 2 3 4 5 6 7 8 9))